<template>
  <v-container class="px-9">
    <v-row>
      <v-col>
        <v-card class="pa-4">
          <h3 class="text-h3 ml-2 mt-2 mb-4">
            Reports
          </h3>
          <v-container class="mt-3">
            <v-card outlined class="pt-4 px-5">
              <!-- Total Earnings -->
              <v-row align-content="space-between">
                <v-col>
                  <h4 class="text-h4">
                    Your Total Earnings
                  </h4>
                </v-col>
                <v-col>
                  <v-btn color="primary" class="float-right" @click="generatePDF">
                    <v-icon>mdi-file-pdf-box</v-icon> Generate PDF
                  </v-btn>
                </v-col>
              </v-row>

              <OrderChart v-if="loaded" :height="100" :order-data="chartData" />
            </v-card>

            <v-card outlined class="pa-4 mt-4">
              <h4 class="text-h4">
                Total: ₱{{ totalEarnings }}
              </h4>
            </v-card>

            <!-- Table -->
            <v-card outlined class="pt-4 px-5 mt-4">
              <v-data-table id="orderTable" :headers="orderHeaders" :items="orderData">
                <template #[`item.user`]="{ item }">
                  {{ item.user.firstname }} {{ item.user.lastname }}
                </template>
                <template #[`item.subtotal`]="{ item }">
                  ₱{{ item.subtotal }}
                </template>
                <template #[`item.server`]="{ item }">
                  <span v-if="item.server">{{ item.server.firstname }}  {{ item.server.lastname }}</span>
                </template>
                <template #[`item.created`]="{ item }">
                  {{ formatDateForDisplay(item.created) }}
                </template>
              </v-data-table>
            </v-card>
          </v-container>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import Moment from 'moment';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import OrderChart from '@/components/charts/OrderChart';

export default {
  name: 'ReportManagement',
  components: {
    OrderChart
  },
  layout: 'admin',
  data () {
    return {
      orderData: [],
      orderHeaders: [
        { value: 'user', text: 'Sold To' },
        { value: 'subtotal', text: 'Subtotal' },
        { value: 'server', text: 'Served by' },
        { value: 'created', text: 'Date' }
      ],
      totalEarnings: 0,
      chartData: [],
      loaded: false
    };
  },
  mounted () {
    this.getOrders();
  },
  methods: {
    async getOrders () {
      const res = await this.$axios.get('/order/list?status=completed');
      this.orderData = res.data.res;
      this.orderData.sort((a, b) => {
        const date1 = new Date(a);
        const date2 = new Date(b);
        return date1 - date2;
      });

      const totalsPerDay = [];
      // console.log(Object.keys(totalsPerDay[0])[0]);

      for (const order of this.orderData) {
        if (!order.created) {
          continue;
        }

        this.totalEarnings += order.subtotal;
        const dateCreated = new Moment(order.created).format('MM-DD-YYYY');

        const dateExists = totalsPerDay.some((o) => {
          return Object.keys(o)[0] === dateCreated;
        });
        if (dateExists) {
          totalsPerDay[dateCreated] += order.subtotal;
        } else {
          const newDay = {};
          newDay[dateCreated] = order.subtotal;
          totalsPerDay.push(newDay);
        }
      }

      this.chartData = totalsPerDay;
      this.loaded = true;
    },
    formatDateForDisplay (date) {
      if (!date) { return '-'; } else {
        return new Moment(date).format('MM-DD-YYYY');
      }
    },
    generatePDF () {
      // eslint-disable-next-line new-cap
      const doc = new jsPDF();

      const toPDFData = [];
      for (const order of this.orderData) {
        const user = order.user ? order.user.firstname + ' ' + order.user.lastname : '-';
        const admin = order.server ? order.server.firstname + ' ' + order.server.lastname : '-';
        const date = this.formatDateForDisplay(order.created);
        const subtotal = 'PHP' + order.subtotal;
        const output = [user, subtotal, admin, date];
        toPDFData.push(output);
      }
      const generatedDate = new Moment().format('MM-DD-YYYY');
      const generatedString = 'Date: ' + generatedDate;
      const generatedBy = 'Generated by: ' + this.$cookies.get('admin').firstname + ' ' + this.$cookies.get('admin').lastname;
      const email = 'Email: ' + this.$cookies.get('admin').email;
      doc.text('Infiniscan Report', 15, 30);
      doc.setFontSize(10);
      doc.text(generatedString, 15, 45);
      doc.text(generatedBy, 15, 50);
      doc.text(email, 15, 55);
      doc.autoTable({
        head: [['Sold To', 'Subtotal', 'Served by', 'Date']],
        body: toPDFData,
        theme: 'grid',
        startY: 60
      });
      const title = 'Infiniscan Report  - ' + generatedDate + '.pdf';
      doc.save(title);
    }
  }
};
</script>

<style>

</style>
